### ISSUE TITLE
Possible performance improvements

### ISSUE THREAD

**Issue by DorijanH** [Enterwell/react-starter#47]
I noticed the following message in the console while using the starter:

```
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
```

Turns out that because of the `.babelrc` configuration file in the root of the project, Next.js thought the starter had a custom Babel configuration and automatically refused to use SWC for files compilation in place of using Babel. 

According to the [documentation](https://nextjs.org/docs/advanced-features/customizing-babel-config) Next.js includes the `next/babel` preset by default. So, in the case we don't need to customize Babel configuration, we should delete the file in order to get sweet Next.js 12 [benefits](https://nextjs.org/blog/next-12#faster-builds-and-fast-refresh-with-rust-compiler).

I made some measurements with and without using SWC and saw the following results (each measurement value is an average of 3 runs; `.next` folder was deleted between each of them):

|    | `yarn build` | `yarn dev` |
| ----------- | ----------- | ----------- |
| Babel | 23.6s | 6.4s |
| SWC | 21.4s | 4.4s |

Futhermore, I noticed the following when running `yarn build` or `yarn dev`

```
postcss-resolve-url: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

Which, be it the right way or not, I resolved by deleting the `yarn.lock` file and generating it from scratch using `yarn install`. With this fresh `yarn.lock` file I noticed futher performance benefits:

| | `yarn build` | `yarn dev` |
| ----------- | ----------- | ----------- |
| Fresh `yarn.lock` | 17.6s | 3.8s |

So, should we delete `.babelrc` file from the starter and is it possible that the newly generated `yarn.lock` file caused such performance increase?

**Comment by AleksandarDev** [comment]
@DorijanH Deleting yarnlock and installing again would install updates for all packages, that's why you see change in performance here. Consider https://github.com/Enterwell/react-starter/pull/44 for proper dependency updating strategy.

As you can see from image below, there is an update available for me next, sass, babel and more:
![image](https://user-images.githubusercontent.com/643171/149583217-33096226-5af5-448d-b906-83b8ef34b404.png)

Deleting custom babelrc is great idea, because we probably don't need any custom plugins.
